import type { ActivityLog, LeaderboardRow, Player } from "@/game/types";

/** Mock operations data for the admin prototype. Replaced by REST + Socket.IO. */
export const MOCK_LEADERBOARD: LeaderboardRow[] = [
  {
    rank: 1,
    playerId: "p_arv",
    playerName: "Arvind Rao",
    team: "Byte Nomads",
    level: 6,
    timeSeconds: 1284,
    penaltySeconds: 75,
    finalTimeSeconds: 1359,
    location: "Main Building / Corridor",
    status: "solving",
  },
  {
    rank: 2,
    playerId: "p_meh",
    playerName: "Meher Nair",
    team: "Null Pointers",
    level: 5,
    timeSeconds: 1310,
    penaltySeconds: 60,
    finalTimeSeconds: 1370,
    location: "Cafeteria / Dining",
    status: "searching",
  },
  {
    rank: 3,
    playerId: "p_ish",
    playerName: "Ishan Verma",
    team: "Quantum Owls",
    level: 5,
    timeSeconds: 1402,
    penaltySeconds: 45,
    finalTimeSeconds: 1447,
    location: "Robotics Lab / Assembly Bay",
    status: "solving",
  },
  {
    rank: 4,
    playerId: "p_tan",
    playerName: "Tanya Iyer",
    team: "Stack Overflow",
    level: 4,
    timeSeconds: 1498,
    penaltySeconds: 90,
    finalTimeSeconds: 1588,
    location: "Auditorium / Stage Hall",
    status: "searching",
  },
  {
    rank: 5,
    playerId: "p_dev",
    playerName: "Dev Kulkarni",
    team: "Kernel Panic",
    level: 3,
    timeSeconds: 1620,
    penaltySeconds: 120,
    finalTimeSeconds: 1740,
    location: "Computer Lab / Lab A",
    status: "solving",
  },
  {
    rank: 6,
    playerId: "p_sar",
    playerName: "Sara Fernandes",
    team: "Deep Field",
    level: 2,
    timeSeconds: 1705,
    penaltySeconds: 30,
    finalTimeSeconds: 1735,
    location: "Library / Reading Hall",
    status: "searching",
  },
  {
    rank: 7,
    playerId: "p_rah",
    playerName: "Rahul Menon",
    team: "Zero Day",
    level: 1,
    timeSeconds: 0,
    penaltySeconds: 0,
    finalTimeSeconds: 0,
    location: "Main Gate",
    status: "not_started",
  },
];

export const MOCK_PLAYERS: Record<string, Player> = Object.fromEntries(
  MOCK_LEADERBOARD.map((row) => [
    row.playerId,
    {
      id: row.playerId,
      enrollmentNumber: `EN${1000 + row.rank}`,
      playerName: row.playerName,
      team: row.team,
      eventId: "techfest-2026",
      status: row.status,
      currentLevel: row.level,
      currentBuilding: "library",
      currentRoom: row.location,
      startTime: Date.now() - row.timeSeconds * 1000,
      endTime: null,
      gameTimeSeconds: row.timeSeconds,
      penaltySeconds: row.penaltySeconds,
      finalTimeSeconds: row.finalTimeSeconds,
      inventory: row.level > 3 ? ["usb_drive", "access_card"] : ["usb_drive"],
    } satisfies Player,
  ]),
);

export const MOCK_ACTIVITY: ActivityLog[] = [
  { type: "level_completed", playerId: "p_arv", playerName: "Arvind Rao", message: "completed Level 5 - Table Talk" },
  { type: "wrong_answer", playerId: "p_dev", playerName: "Dev Kulkarni", message: "wrong answer on Binary challenge (+30s)" },
  { type: "hint_used", playerId: "p_tan", playerName: "Tanya Iyer", message: "used Hint 2 (+30s)" },
  { type: "object_investigated", playerId: "p_sar", playerName: "Sara Fernandes", message: "investigated Filing Cabinet" },
  { type: "clue_found", playerId: "p_ish", playerName: "Ishan Verma", message: "found trace in Toolbox" },
  { type: "item_collected", playerId: "p_meh", playerName: "Meher Nair", message: "collected Access Card" },
  { type: "room_entered", playerId: "p_sar", playerName: "Sara Fernandes", message: "entered Library / Reading Hall" },
  { type: "player_started", playerId: "p_dev", playerName: "Dev Kulkarni", message: "started the hunt" },
].map((e, i) => ({
  ...e,
  id: `mock_${i}`,
  createdAt: Date.now() - i * 47_000,
})) as ActivityLog[];

export const MOCK_ANALYTICS = {
  perLevel: Array.from({ length: 10 }, (_, i) => ({
    level: `L${i + 1}`,
    avgTime: Math.round(140 + i * 26 + (i % 3) * 18),
    avgPenalty: Math.round(18 + i * 6),
    successRate: Math.max(38, 96 - i * 5),
  })),
  usage: [
    { name: "Hints", value: 148 },
    { name: "Scanner", value: 96 },
    { name: "Retries", value: 211 },
  ],
  locations: [
    { name: "Library", visits: 132 },
    { name: "Computer Lab", visits: 118 },
    { name: "Robotics Lab", visits: 104 },
    { name: "Auditorium", visits: 76 },
    { name: "Cafeteria", visits: 61 },
    { name: "Server Room", visits: 34 },
  ],
};